services:
    p6-db-1:
        image: p6-base
        container_name: p6-db-1
        hostname: p6-db-1
        volumes:
            - "./nb:/nb"
        ports:
            - "127.0.0.1:5000:5000"
        command: sh -c "bash /cassandra.sh & python3 -m jupyterlab --no-browser --ip=0.0.0.0 --port=5000 --allow-root --NotebookApp.token=''"

    p6-db-2:
        image: p6-base
        container_name: p6-db-2
        hostname: p6-db-2

    p6-db-3:
        image: p6-base
        container_name: p6-db-3
        hostname: p6-db-3
