handler:
	gcc mySigHandler.c -Wall -m32 -std=gnu99 -o mySigHandler

send: 
	gcc sendsig.c -Wall -m32 -std=gnu99 -o sendsig

div:
	gcc division.c -Wall -m32 -std=gnu99 -o division

run:
	./mySigHandler