services:
    nb:
        image: p4-nb
        ports:
        - "127.0.0.1:5000:5000"
        volumes:
        - "./nb:/nb"
        deploy:
                resources:
                        limits:
                                memory: 1g

    nn:
        image: p4-nn
        hostname: boss
        deploy:
                resources:
                        limits:
                                memory: 1g

    dn:
        image: p4-dn
        deploy:
                replicas: 2
                resources:
                        limits:
                                memory: 1g

